import type { PostKind } from "@/lib/instagram/types";
import type { Locale } from "@/lib/locale";

export const UI = {
  de: {
    tool: "Video-Tool",
    navTool: "Tool",
    navFeatures: "Funktionen",
    navGuide: "Anleitung",
    navFaq: "FAQ",
    navAria: "Seite",
    navMobileAria: "Mobil",
    menu: "Menü",
    menuOpen: "Menü öffnen",
    menuClose: "Menü schließen",
    menuDescription: "Navigation zu Tool, Funktionen, Anleitung und FAQ",
    langDe: "Deutsch",
    langEn: "English",
    langAria: "Sprache",
    footerLead:
      "MP4 Video Downloader für öffentliche Instagram Reels, YouTube-Videos, Shorts und TikToks — original, ohne Wasserzeichen, ohne Konto.",
    footerLegal: "Rechtliches",
    footerTools: "Downloader",
    imprint: "Impressum",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
    copyright: "© 2026 Rille",
    footerNote:
      "Nur öffentliche Inhalte. Private Profile und geschützte Videos bleiben gesperrt. Nutze Dateien nur, wenn du dazu berechtigt bist. Rille ist nicht mit Meta, Google oder ByteDance verbunden.",
    featuresEyebrow: "Funktionen",
    featuresTitle: (label: string) => `${label} im Überblick.`,
    guideEyebrow: "Anleitung",
    guideTitle: (label: string) => `${label} herunterladen: drei Schritte.`,
    seoEyebrow: "Ratgeber",
    faqEyebrow: "FAQ",
    faqTitle: (label: string) => `${label} — kurz beantwortet.`,
    demoTitle: "So sieht dein Ergebnis aus",
    demoSub: (label: string) => `${label} · Vorschau und Sichern.`,
    demoBadge: "Beispielansicht",
    demoLoad: "Beispiel laden",
    results: "Ergebnisse",
    filesReady: (n: number) => (n === 1 ? "1 Datei bereit" : `${n} Dateien bereit`),
    saveAll: "Alle sichern",
    saveAllStart: (n: number) => `Starte ${n} Datei${n === 1 ? "" : "en"}…`,
    clear: "Leeren",
    history: "Zuletzt geladen",
    clearHistory: "Verlauf löschen",
    again: "Erneut",
    save: "Sichern",
    saving: "Sichert…",
    notLoaded: "Nicht geladen",
    retry: "Erneut versuchen",
    remove: "Entfernen",
    paste: "Zwischenablage einfügen",
    pasteInto: (n: number) => `Zwischenablage in Feld ${n} einfügen`,
    removeField: (n: number) => `Feld ${n} entfernen`,
    emptyClipboard: "Zwischenablage ist leer.",
    pasted: "Link eingefügt.",
    pastedN: (n: number) => `${n} Links eingefügt.`,
    noClipboard: "Zwischenablage ist nicht verfügbar.",
    moreLink: "Weiterer Link",
    example: "Beispiel",
    format: "Format",
    load: "laden",
    linkN: (n: number) => `Link ${n}`,
    linkFor: (label: string) => `${label}-Link`,
    switched: (label: string) => `Zu ${label} gewechselt.`,
    onlyThis: (label: string) => `Nur ${label}-Links in diesem Bereich.`,
    noValid: (label: string) => `Kein gültiger ${label}-Link gefunden.`,
    invalidField: (label: string) => `Das sieht nicht nach einem ${label}-Link aus.`,
    maxBatch: "Maximal 12 Links pro Stapel.",
    loadedOne: "1 Medium geladen.",
    loadedN: (n: number) => `${n} Medien geladen.`,
    failedN: (n: number) => `${n} Link${n === 1 ? "" : "s"} fehlgeschlagen.`,
    requestFailed: "Die Anfrage ist fehlgeschlagen. Bitte erneut versuchen.",
    saveFail: "Sichern fehlgeschlagen.",
    shareOk: "Teilen-Menü ist offen. Dort „In Fotos sichern“ tippen.",
    downloadOk: "Download gestartet.",
    appleHint: "iPhone: Sichern öffnet das Teilen-Menü. Dort „In Fotos sichern“ wählen.",
    loading: ["Link wird geprüft", "Quelle wird abgefragt", "Datei wird vorbereitet"],
    loadingTimeout: "Das dauert zu lange. Bitte erneut versuchen.",
    abort: "Abbrechen",
    aborted: "Abgebrochen.",
    readySuffix: "bereit",
    notFoundTitle: "Seite nicht gefunden.",
    notFoundBody: "Diese Adresse gibt es bei Rille nicht. Zurück zu den drei Tools.",
    backHome: "Zur Startseite",
    errorTitle: "Etwas ist schiefgegangen",
    errorFallback: "Unerwarteter Fehler. Seite neu laden.",
    files: (n: number) => `${n} Datei${n === 1 ? "" : "en"}`,
    backToTool: "Zurück zum Tool",
    platformAria: "Plattform",
    kind: {
      reel: "Reel",
      post: "Beitrag",
      carousel: "Karussell",
      story: "Story",
      video: "Video",
      photo: "Foto",
      youtube: "YouTube",
      short: "Short",
      tiktok: "TikTok",
    } satisfies Record<PostKind, string>,
  },
  en: {
    tool: "Video tool",
    navTool: "Tool",
    navFeatures: "Features",
    navGuide: "Guide",
    navFaq: "FAQ",
    navAria: "Page",
    navMobileAria: "Mobile",
    menu: "Menu",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    menuDescription: "Navigation to the tool, features, guide and FAQ",
    langDe: "Deutsch",
    langEn: "English",
    langAria: "Language",
    footerLead:
      "MP4 downloader for public Instagram Reels, YouTube videos, Shorts and TikToks — original files, no watermark, no account.",
    footerLegal: "Legal",
    footerTools: "Downloaders",
    imprint: "Imprint",
    privacy: "Privacy",
    terms: "Terms",
    copyright: "© 2026 Rille",
    footerNote:
      "Public media only. Private profiles and protected videos stay locked. Only save files you are allowed to keep. Rille is not affiliated with Meta, Google or ByteDance.",
    featuresEyebrow: "Features",
    featuresTitle: (label: string) => `${label} at a glance.`,
    guideEyebrow: "How it works",
    guideTitle: (label: string) => `Download ${label} in three steps.`,
    seoEyebrow: "Guide",
    faqEyebrow: "FAQ",
    faqTitle: (label: string) => `${label} — short answers.`,
    demoTitle: "This is how your result looks",
    demoSub: (label: string) => `${label} · Preview and save.`,
    demoBadge: "Sample preview",
    demoLoad: "Load sample",
    results: "Results",
    filesReady: (n: number) => (n === 1 ? "1 file ready" : `${n} files ready`),
    saveAll: "Save all",
    saveAllStart: (n: number) => `Starting ${n} file${n === 1 ? "" : "s"}…`,
    clear: "Clear",
    history: "Recently loaded",
    clearHistory: "Clear history",
    again: "Again",
    save: "Save",
    saving: "Saving…",
    notLoaded: "Not loaded",
    retry: "Try again",
    remove: "Remove",
    paste: "Paste from clipboard",
    pasteInto: (n: number) => `Paste clipboard into field ${n}`,
    removeField: (n: number) => `Remove field ${n}`,
    emptyClipboard: "Clipboard is empty.",
    pasted: "Link pasted.",
    pastedN: (n: number) => `${n} links pasted.`,
    noClipboard: "Clipboard is not available.",
    moreLink: "Another link",
    example: "Sample",
    format: "Format",
    load: "load",
    linkN: (n: number) => `Link ${n}`,
    linkFor: (label: string) => `${label} link`,
    switched: (label: string) => `Switched to ${label}.`,
    onlyThis: (label: string) => `Only ${label} links in this section.`,
    noValid: (label: string) => `No valid ${label} link found.`,
    invalidField: (label: string) => `That doesn’t look like a ${label} link.`,
    maxBatch: "Maximum 12 links per batch.",
    loadedOne: "1 item loaded.",
    loadedN: (n: number) => `${n} items loaded.`,
    failedN: (n: number) => `${n} link${n === 1 ? "" : "s"} failed.`,
    requestFailed: "The request failed. Please try again.",
    saveFail: "Saving failed.",
    shareOk: "Share sheet is open. Tap “Save to Photos”.",
    downloadOk: "Download started.",
    appleHint: "iPhone: Save opens the share sheet. Choose “Save to Photos”.",
    loading: ["Checking the link", "Asking the source", "Preparing the file"],
    loadingTimeout: "This is taking too long. Please try again.",
    abort: "Cancel",
    aborted: "Cancelled.",
    readySuffix: "ready",
    notFoundTitle: "Page not found.",
    notFoundBody: "This address doesn’t exist on Rille. Back to the three tools.",
    backHome: "Go to home",
    errorTitle: "Something went wrong",
    errorFallback: "Unexpected error. Reload the page.",
    files: (n: number) => `${n} file${n === 1 ? "" : "s"}`,
    backToTool: "Back to the tool",
    platformAria: "Platform",
    kind: {
      reel: "Reel",
      post: "Post",
      carousel: "Carousel",
      story: "Story",
      video: "Video",
      photo: "Photo",
      youtube: "YouTube",
      short: "Short",
      tiktok: "TikTok",
    } satisfies Record<PostKind, string>,
  },
} as const;

export function uiCopy(locale: Locale) {
  return UI[locale] ?? UI.de;
}
