/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as InstagramReelsRouteImport } from './routes/instagram-reels'
import { Route as NutzungRouteImport } from './routes/nutzung'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as TiktokDownloaderRouteImport } from './routes/tiktok-downloader'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as YoutubeMp4RouteImport } from './routes/youtube-mp4'
import { Route as ApiFileRouteImport } from './routes/api/file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramReelsRoute = InstagramReelsRouteImport.update({
  id: '/instagram-reels',
  path: '/instagram-reels',
  getParentRoute: () => rootRouteImport,
} as any)
const NutzungRoute = NutzungRouteImport.update({
  id: '/nutzung',
  path: '/nutzung',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokDownloaderRoute = TiktokDownloaderRouteImport.update({
  id: '/tiktok-downloader',
  path: '/tiktok-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeMp4Route = YoutubeMp4RouteImport.update({
  id: '/youtube-mp4',
  path: '/youtube-mp4',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/instagram': typeof InstagramRoute
  '/instagram-reels': typeof InstagramReelsRoute
  '/nutzung': typeof NutzungRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiktok': typeof TiktokRoute
  '/tiktok-downloader': typeof TiktokDownloaderRoute
  '/youtube': typeof YoutubeRoute
  '/youtube-mp4': typeof YoutubeMp4Route
  '/api/file': typeof ApiFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/instagram': typeof InstagramRoute
  '/instagram-reels': typeof InstagramReelsRoute
  '/nutzung': typeof NutzungRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiktok': typeof TiktokRoute
  '/tiktok-downloader': typeof TiktokDownloaderRoute
  '/youtube': typeof YoutubeRoute
  '/youtube-mp4': typeof YoutubeMp4Route
  '/api/file': typeof ApiFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/instagram': typeof InstagramRoute
  '/instagram-reels': typeof InstagramReelsRoute
  '/nutzung': typeof NutzungRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiktok': typeof TiktokRoute
  '/tiktok-downloader': typeof TiktokDownloaderRoute
  '/youtube': typeof YoutubeRoute
  '/youtube-mp4': typeof YoutubeMp4Route
  '/api/file': typeof ApiFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/instagram'
    | '/instagram-reels'
    | '/nutzung'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tiktok'
    | '/tiktok-downloader'
    | '/youtube'
    | '/youtube-mp4'
    | '/api/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/instagram'
    | '/instagram-reels'
    | '/nutzung'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tiktok'
    | '/tiktok-downloader'
    | '/youtube'
    | '/youtube-mp4'
    | '/api/file'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/instagram'
    | '/instagram-reels'
    | '/nutzung'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tiktok'
    | '/tiktok-downloader'
    | '/youtube'
    | '/youtube-mp4'
    | '/api/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  InstagramRoute: typeof InstagramRoute
  InstagramReelsRoute: typeof InstagramReelsRoute
  NutzungRoute: typeof NutzungRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiktokRoute: typeof TiktokRoute
  TiktokDownloaderRoute: typeof TiktokDownloaderRoute
  YoutubeRoute: typeof YoutubeRoute
  YoutubeMp4Route: typeof YoutubeMp4Route
  ApiFileRoute: typeof ApiFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-reels': {
      id: '/instagram-reels'
      path: '/instagram-reels'
      fullPath: '/instagram-reels'
      preLoaderRoute: typeof InstagramReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutzung': {
      id: '/nutzung'
      path: '/nutzung'
      fullPath: '/nutzung'
      preLoaderRoute: typeof NutzungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-downloader': {
      id: '/tiktok-downloader'
      path: '/tiktok-downloader'
      fullPath: '/tiktok-downloader'
      preLoaderRoute: typeof TiktokDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube-mp4': {
      id: '/youtube-mp4'
      path: '/youtube-mp4'
      fullPath: '/youtube-mp4'
      preLoaderRoute: typeof YoutubeMp4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  InstagramRoute: InstagramRoute,
  InstagramReelsRoute: InstagramReelsRoute,
  NutzungRoute: NutzungRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiktokRoute: TiktokRoute,
  TiktokDownloaderRoute: TiktokDownloaderRoute,
  YoutubeRoute: YoutubeRoute,
  YoutubeMp4Route: YoutubeMp4Route,
  ApiFileRoute: ApiFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
